sprint-1
prismgentem/smart-residence-activity pull request #1
Opened 2024-10-06 10:00 UTC by prismgentem

2024-10-16 06:15 UTC, SHvatov commented
Привет!
По поводу архитектуры - я бы сделал два сервиса по нотификациям - а-ля через email и через телегу. Второй можно сразу не реализовывать (только если будешь успевать), но основу под него я бы заложил. В остальном все ОК)

2024-10-16 06:26 UTC, SHvatov requested changes
@prismgentem, оставил пару минорных комментариев, а так 🔥 Еще бы докер-компоуз докинуть, и вообще было бы 🚀

2024-10-16 06:26 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/Admin.java
> +@Getter
Советую ознакомиться, и посмотреть, что никакие грабли ты не задел)
- https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/
- https://habr.com/ru/companies/haulmont/articles/564682/

2024-10-16 06:26 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/Admin.java
> +    @OneToMany(mappedBy = "createdBy", cascade = CascadeType.ALL, orphanRemoval = true)
`Lazy` не хочешь накинуть, чтобы не тянуть все 100_500 записей, которые создал конкретный админ?)

2024-10-16 06:26 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/Request.java
> +public class Request extends BaseEntityCU {
Тут либо джава-док с описанием, что за сущность, либо чуть более говорящее название) На что этот запрос? Видимо на какую-то услугу?

2024-10-16 06:26 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/base/BaseEntityCU.java
> +public abstract class BaseEntityCU extends BaseEntity{
Пробельчик забыли)

2024-10-16 06:26 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/base/BaseEntity.java
> +        if (isNull(o) || Hibernate.getClass(this) != Hibernate.getClass(o)) {
я бы в самую первую очередь на null чекнул, строке так на 35, а дальше бы работал уже с ненуловым объектом

2024-10-16 06:26 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/base/BaseEntity.java
> +        if (isNull(o) || Hibernate.getClass(this) != Hibernate.getClass(o)) {
ультра фэйл-фаст поведение)

2024-10-16 06:26 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/base/BaseEntityCU.java
> +public abstract class BaseEntityCU extends BaseEntity{
И что значит `CU`?) Я бы, по классике, назвал сущность `Audited...`. Только вот нужен ли тут тебе аудит?)

2024-10-16 06:34 UTC, prismgentem commented on src/main/java/org/example/smartresidenceactivity/entity/base/BaseEntity.java
> +        if (isNull(o) || Hibernate.getClass(this) != Hibernate.getClass(o)) {
Привет, немного не понял, что значит "Ультра фейл-фаст поведение"

2024-10-16 06:55 UTC, prismgentem commented on src/main/java/org/example/smartresidenceactivity/entity/base/BaseEntityCU.java
> +public abstract class BaseEntityCU extends BaseEntity{
CU - Create Update, думаю название Audit немного не подходит, тк в аудит я бы ещё добавил электронную почту или допустим ФИО того, кто обновлял сущность, а Create Update это на будущее, думаю где-нибудь выскачет потребность в этой информации.

2024-10-16 12:33 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/base/BaseEntity.java
> +        if (isNull(o) || Hibernate.getClass(this) != Hibernate.getClass(o)) {
Просто так проверки явно разбиты на логические ступени, а-ля:
-  чекнуть что второй объект - null
- чекнуть на равенство ссылок
- проверить, что классы одни и те же
- ....

2024-10-17 18:16 UTC, prismgentem commented on src/main/java/org/example/smartresidenceactivity/entity/Admin.java
> +@Getter
Правильно понимаю что лучше не использовать аннотацию @Accessors(chain = true) с JPA сущностями, тк эта аннотация изменят сеттеры и вместо void отдаёт объект, что может вызвать проблемы при использовании допустим Jackson или JPA?

2024-11-10 07:17 UTC, SHvatov commented on src/main/java/org/example/smartresidenceactivity/entity/Admin.java
> +@Getter
Обсудили на синке)

2024-11-10 07:17 UTC, SHvatov commented
@prismgentem давай этот МР уже смерджим, чтобы глаза не мозолил)

2024-12-03 17:49 UTC, merged